---
services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.2.1
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
      - WEBUI_PORT=8090
    volumes:
      - ${CONFIG_DIR}:/config
      - /mnt/media-dir:/data
    network_mode: container:gluetun
    restart: unless-stopped
