---
version: "2.1"
services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}:/app/config
    networks:
      - teleport_teleport
    restart: unless-stopped

networks:
  teleport_teleport:
    external: true
