version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - {{ CONFIG_DIR }}:/config
    networks:
      - teleport
    restart: unless-stopped

networks:
  teleport:
    external: true
