---
services:
  prowlarr:
    image: linuxserver/prowlarr:2.4.0
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
    volumes:
      - ${CONFIG_DIR}:/config
    networks:
      teleport_teleport:
    restart: unless-stopped

networks:
  teleport_teleport:
    external: true
