---
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n

    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - ${CONFIG_DIR}:/home/node/.n8n
    networks:
      - teleport

networks:
  teleport:
    external: true
