---
services:
  flaresolverr:
    image: flaresolverr/flaresolverr:v3.5.0
    container_name: flaresolverr
    networks:
      teleport_teleport:
    environment:
      - LOG_LEVEL=info
    restart: always

networks:
  teleport_teleport:
    external: true
